'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("prjAssignment.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bike1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bike1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bike2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bike2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Henry, Morgan, 6/5/1943, m, henry@gmail.com, 3530877188825, Apt1 Tall Building, Main street, cork, cork, Ireland, 8787, annual, Visa Credit, 1415263524352435, 345, 01/03/2019, Henry Morgan, 82.00, 05/03/2016
        '''George, Hook, 6/5/1994, m, Geo@gmail.com, 3530871811176, Apt 12 tall Building, Patrick&apos;s street, Cork, Cork, Ireland, 4352, annual, Visa Credit, 5654543434343434, 566, 01/04/2017, George Hook, 92.00, 05/02/2017
        '''Isla, Fisher, 5/5/1979, f, isla@gmail.com, 3530875628789, 44 Cedar Park, Swords, Address li [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property clients() As String
            Get
                Return ResourceManager.GetString("clients", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To Hire a City Bike
        '''The City Bike service is available all year 7 days a week, from 5am to 12.30am, though a bike can be returned to available stands at any time of the day.
        '''
        '''Log in with either your Subscriber Access number from your 3 Day pass , or present your Membership Card to the card reader on the terminal, then enter your PIN code.
        '''Choose the Bike you wish to use by means of the stand number of an available CityBike.
        '''You are then given the code for the combination lock provided on the City Bike, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HiringABike() As String
            Get
                Return ResourceManager.GetString("HiringABike", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4, 1050, its kinda broke like
        '''10, 1141, no saddle
        '''12, 1170, Rusty bike
        '''8, 1111, front tyre flat
        '''2, 1030, bike broken
        '''5, 1062, no wheels
        '''5, 1042, no basket
        '''2, 1016, broken light
        '''10, 1136, No brakes
        '''6, 1079, Flat tyre
        '''6, 1076, Rusty
        '''5, 1066, Bald tyres
        '''10, 1142, Crooked handlbars
        '''1, 1007, Flat tyre
        '''8, 1121, Wobbly
        '''2, 1019, too small
        '''4, 1047, no spokes
        '''.
        '''</summary>
        Friend ReadOnly Property maintenance() As String
            Get
                Return ResourceManager.GetString("maintenance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to manager
        '''m13310n
        '''maintenance
        '''0rb1t
        '''.
        '''</summary>
        Friend ReadOnly Property Passwords() As String
            Get
                Return ResourceManager.GetString("Passwords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mary, O&apos;Keefe, 9987, 1095, 13/02/2017 23:03:40
        '''Henry, Morgan, 8787, 1156, 14/02/2017 22:02:29
        '''Liam, Wilson, 9008, 1048, 15/02/2017 22:49:20
        '''Liam, Wilson, 9008, 1108, 16/02/2017 11:13:01
        '''.
        '''</summary>
        Friend ReadOnly Property renters() As String
            Get
                Return ResourceManager.GetString("renters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property repaired() As String
            Get
                Return ResourceManager.GetString("repaired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To Return a City Bike
        '''Push the City Bike back into an available stand. An audio beep is emitted and the lights on the bike stand flash momentarily before a continuous green light is displayed. This confirms that the bike has been replaced correctly and the hire has been terminated. If there is a problem, either try to reposition the bike or try another stand..
        '''</summary>
        Friend ReadOnly Property ReturningABike() As String
            Get
                Return ResourceManager.GetString("ReturningABike", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 317.90
        '''.
        '''</summary>
        Friend ReadOnly Property revenue() As String
            Get
                Return ResourceManager.GetString("revenue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0.00, 1001, True, , True, 1003, True, 1004, True, 1005, True, 1006, True, 1007, False, 1008, True, 1009, True, 1010, True, 1011, True, 1012, True, 1013, True, 1014, True, 1015, True
        '''0.00, 1016, False, 1017, True, 1018, True, 1019, False, 1020, True, 1021, True, 1022, True, 1023, True, 1024, True, 1025, True, 1026, True, 1027, True, 1028, True, 1029, True, 1030, False
        '''0.00, 1138, True, 1032, True, 1033, True, 1140, True, 1035, True, 1078, True, 1037, True, 1038, True, 1039, True, 1040, True, 1041, True, 10 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property stations() As String
            Get
                Return ResourceManager.GetString("stations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Henry, Morgan, 6/5/1943, m, henry@gmail.com, 3530877188825, Apt1 Tall Building, Main street, cork, cork, Ireland, 8787, annual, Visa Credit, 1415263524352435, 345, 01/03/2019, Henry Morgan, 10, 05/03/2016
        '''George, Hook, 6/5/1994, m, Geo@gmail.com, 3530871811176, Apt 12 tall Building, Patrick&apos;s street, Cork, Cork, Ireland, 4352, annual, Visa Credit, 5654543434343434, 566, 01/04/2017, George Hook, 92, 05/02/2017
        '''Isla, Fisher, 5/5/1979, f, isla@gmail.com, 3530875628789, 44 Cedar Park, Swords, Address line 3 ( [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property tempclients() As String
            Get
                Return ResourceManager.GetString("tempclients", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1. Introduction
        '''
        '''The National Transport Authority is providing a service (the &quot;Service&quot;) enabling access to self-service hire bicycles in the cities of Galway, Limerick and Cork under public bike share schemes operated as CityBikes.
        '''
        '''The Service is operated on behalf of the National Transport Authority by Telfourth Limited, trading as An Rothar Nua.
        '''
        '''These terms and conditions set out the agreement between you and the National Transport Authority in relation to the opening and operation of an account  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TermsAndConditions() As String
            Get
                Return ResourceManager.GetString("TermsAndConditions", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
